<?php
$this->headTitle('Edit User');
//$this->mainMenu()->setActiveItemId('users');
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home'),
//            'Manage Users'=>$this->url('users'),
//            'Edit User'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
//            ]);
$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ]);
$form->get('full_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'John Doe'
    ]);
$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);
$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');
$form->prepare();
?>
<section class="content-header col-md-offset-1">
<h1>Edit User <?= $this->escapeHtml($user->getEmail()) ?></h1>
</section>

<section class="content">
<div class="row">
    <div class="col-md-10 col-md-offset-1">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Quick Example</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <div class="box-body">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>           </div>
          </div>

        </div>
   
</div>   
</section>