<?php
$this->headTitle('View Qualification');
//$this->mainMenu()->setActiveItemId('users');
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home'),
//            'Manage Users'=>$this->url('users'),
//            'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
//            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<section class="content-header"><h1>View Qualification</h1></section>

<section class="content">
<div class="row">
<div class="col-md-6">
          <div class="box box-solid">
            <div class="box-header with-border">
              <i class="fa fa-text-width"></i>

              <h3 class="box-title">Details</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($qualification->getId()) ?></th>
            </tr>
            <tr>
                <th>Qualification:</th>
                <td><?= $this->escapeHtml($qualification->getQualification()) ?></th>
            </tr>
            
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($qualification->getDateCreated()) ?></th>
            </tr>
           
        </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
</div>
    </section>


