<?php
$this->headTitle('View Practice');
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<section class="content-header"><h1>View Practice Detail</h1></section>

<section class="content">
<div class="row">
<div class="col-md-6">
          <div class="box box-solid">
            <div class="box-header with-border">
              <i class="fa fa-text-width"></i>

              <h3 class="box-title">Details</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
        <table class="table table-striped table-bordered">
             <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($practice->getPracticeName()) ?></th>
            </tr>
            <tr>
                <th>Description:</th>
                <td><?= $this->escapeHtml($practice->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Address:</th>
                <td><?= $this->escapeHtml($practice->getAddress()) ?></th>
            </tr>
            <tr>
                <th>State:</th>
                <td><?= $this->escapeHtml($practice->getState()) ?></th>
            </tr>
            <tr>
                <th>Suburb:</th>
                <td><?= $this->escapeHtml($practice->getSuburb()) ?></th>
            </tr>
            <tr>
                <th>Postal Code:</th>
                <td><?= $this->escapeHtml($practice->getPostalCode()) ?></th>
            </tr>
            
            <tr>
                <th>Phone Number:</th>
                <td><?= $this->escapeHtml($practice->getPhoneNumber()) ?></th>
            </tr>

            <tr>
                <th>Language:</th>
                <td><?= $this->escapeHtml($practice->getLanguages()) ?></th>
            </tr>
            
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($practice->getDateCreated()) ?></th>
            </tr>

        </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
</div>
    </section>


